/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagement;

import data.Book;
import data.BookData;
import data.Borrow;
import data.BorrowData;
import data.JDBC_Connection;
import data.User;
import data.UserData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author qinee
 */
public class AdminHome extends javax.swing.JFrame {

    public static PreparedStatement pst;
    public static PreparedStatement ps2 = null;
    public static ResultSet rs;
    public static String sqlBook = "SELECT * FROM BookList order by code asc";
    public static String sqlBorrow = "SELECT * FROM BorrowList order by BorrowCode asc";
    public static String sqlUser = "SELECT * FROM UserAccount order by id asc";

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
        GetBooklist();
        GetBorrowList();
        GetUserList();
        Update.LoadData(sqlBook, tbBook);
        Update.LoadData(sqlUser, tbUser);
        Update.LoadData(sqlBorrow, tbBorrow);
        ProcessCrt(false);
        ProcessCrt2(false);
        ProcessCrt3(false);
    }

    public void ProcessCrt(boolean b) {
        this.btAddBook.setEnabled(true);
        this.btUpdateBook.setEnabled(b);
        this.btDeleteBook.setEnabled(b);
    }

    public void ProcessCrt2(boolean b) {
        this.btAddUser.setEnabled(true);
        this.btUpdateUser.setEnabled(b);
        this.btDeleteUser.setEnabled(b);
    }

    public void ProcessCrt3(boolean b) {
        this.btAddBorrow.setEnabled(true);
        this.btUpdateBorrow.setEnabled(b);
        this.btDeleteBorrow.setEnabled(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbBook = new javax.swing.JTable();
        tfSearch = new javax.swing.JTextField();
        btSearchBook = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        tfCode = new javax.swing.JTextField();
        tfBookName = new javax.swing.JTextField();
        tfAuthor = new javax.swing.JTextField();
        tfPublish = new javax.swing.JTextField();
        tfEdition = new javax.swing.JTextField();
        tfCost = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfQuantity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btAddBook = new javax.swing.JButton();
        btUpdateBook = new javax.swing.JButton();
        btDeleteBook = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbBorrow = new javax.swing.JTable();
        tfSearchBorrow = new javax.swing.JTextField();
        btSearchBorrow = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        tfBorrowCode = new javax.swing.JTextField();
        tfBorrowID = new javax.swing.JTextField();
        tfBookCode = new javax.swing.JTextField();
        tfBorrowDate = new javax.swing.JTextField();
        tfReturnDate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btAddBorrow = new javax.swing.JButton();
        btUpdateBorrow = new javax.swing.JButton();
        btDeleteBorrow = new javax.swing.JButton();
        btReturn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbUser = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        btAddUser = new javax.swing.JButton();
        btUpdateUser = new javax.swing.JButton();
        btDeleteUser = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        tfUserID = new javax.swing.JTextField();
        tfPass = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tfBirthday = new javax.swing.JTextField();
        tfIdentityNumber = new javax.swing.JTextField();
        tfPhoneNumber = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfAddress = new javax.swing.JTextArea();
        btSearchUser = new javax.swing.JButton();
        tfSearchUser = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Code", "Name", "Author", "Publish", "Edition", "Cost", "Quantity"
            }
        ));
        tbBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBookMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbBook);

        btSearchBook.setText("Search");
        btSearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchBookActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Information"));

        jLabel1.setText("Code");

        jLabel2.setText("Name");

        jLabel3.setText("Author");

        jLabel4.setText("Publish");

        jLabel5.setText("Edition");

        jLabel6.setText("Cost");

        jLabel7.setText("Quantity");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(tfPublish, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCode, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCost, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(tfEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPublish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Operation"));

        btAddBook.setText("Add");
        btAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddBookActionPerformed(evt);
            }
        });

        btUpdateBook.setText("Update");
        btUpdateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateBookActionPerformed(evt);
            }
        });

        btDeleteBook.setText("Delete");
        btDeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(btUpdateBook, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btDeleteBook, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAddBook)
                    .addComponent(btUpdateBook)
                    .addComponent(btDeleteBook))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btSearchBook)
                .addContainerGap(67, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSearchBook))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Book List", jPanel2);

        tbBorrow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Borrow Code", "ID", "Book Code", "Borrow Date", "Return Date"
            }
        ));
        tbBorrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBorrowMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbBorrow);

        btSearchBorrow.setText("Search");
        btSearchBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchBorrowActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Information"));

        tfBorrowID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBorrowIDActionPerformed(evt);
            }
        });

        jLabel8.setText("Borrow Code");

        jLabel9.setText("ID");

        jLabel10.setText("Book Code");

        jLabel12.setText("Borrow Date");

        jLabel13.setText("Return Date");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfBorrowID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(tfBorrowCode, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfBookCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfBorrowDate, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(tfBorrowCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tfBorrowID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(tfReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfBookCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfBorrowDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Operation"));

        btAddBorrow.setText("Add");
        btAddBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddBorrowActionPerformed(evt);
            }
        });

        btUpdateBorrow.setText("Update");
        btUpdateBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateBorrowActionPerformed(evt);
            }
        });

        btDeleteBorrow.setText("Delete");
        btDeleteBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteBorrowActionPerformed(evt);
            }
        });

        btReturn.setText("Return");
        btReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btAddBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(btUpdateBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btDeleteBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAddBorrow)
                    .addComponent(btUpdateBorrow)
                    .addComponent(btDeleteBorrow)
                    .addComponent(btReturn))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(tfSearchBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btSearchBorrow)
                .addContainerGap(64, Short.MAX_VALUE))
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSearchBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSearchBorrow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 1, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 2, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Borrow List", jPanel3);

        tbUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Password", "Full Name", "Birthday", "Identity Number", "Phone Number", "Address"
            }
        ));
        tbUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUserMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbUser);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Operation"));

        btAddUser.setText("Add");
        btAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddUserActionPerformed(evt);
            }
        });

        btUpdateUser.setText("Update");
        btUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateUserActionPerformed(evt);
            }
        });

        btDeleteUser.setText("Delete");
        btDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(btUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAddUser)
                    .addComponent(btUpdateUser)
                    .addComponent(btDeleteUser))
                .addContainerGap())
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Information"));

        tfPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPassActionPerformed(evt);
            }
        });

        jLabel11.setText("ID");

        jLabel14.setText("Password");

        jLabel15.setText("Full Name");

        jLabel16.setText("Birthday");

        jLabel17.setText("Identity Number");

        jLabel18.setText("Phone Number");

        jLabel19.setText("Address");

        tfAddress.setColumns(20);
        tfAddress.setRows(5);
        jScrollPane1.setViewportView(tfAddress);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(tfBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfIdentityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfIdentityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))
                .addContainerGap())
        );

        btSearchUser.setText("Search");
        btSearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(tfSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btSearchUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSearchUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("User List", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSearchUserActionPerformed

    private void tfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPassActionPerformed

    private void btDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteUserActionPerformed
        // TODO add your handling code here:
        if (this.tfUserID.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Please input User ID!", "Message", 2);
        } else if (this.tfUserID.getText().length() != 6) {
            JOptionPane.showMessageDialog(null, "Please insert 6 characters!", "Message", 2);
        } else {
            if (UserData.DeleteUser(this.tfUserID.getText())) {
                JOptionPane.showMessageDialog(null, "Deleted", "Message", 1);
            } else {
                JOptionPane.showMessageDialog(null, "Error. Please try again!", "Message", 2);
            }
            this.btSearchUser.doClick();
        }
    }//GEN-LAST:event_btDeleteUserActionPerformed

    private void btUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateUserActionPerformed
        // TODO add your handling code here:
        if (this.tfUserID.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Please input User ID!", "Message", 2);
        } else if (this.tfUserID.getText().length() != 6) {
            JOptionPane.showMessageDialog(null, "Please insert 6 characters!", "Message", 2);
        } else {
            User user = new User(this.tfUserID.getText(), this.tfPass.getText(), this.tfName.getText(), this.tfBirthday.getText(),
                this.tfIdentityNumber.getText(), this.tfPhoneNumber.getText(), this.tfPhoneNumber.getText());
            if (UserData.UpdateUser(user)) {
                JOptionPane.showMessageDialog(null, "Updated!", "Message", 1);
            } else {
                JOptionPane.showMessageDialog(null, "Error. Please try again!", "Message", 2);
            }
            this.btSearchUser.doClick();
        }
    }//GEN-LAST:event_btUpdateUserActionPerformed

    private void btAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddUserActionPerformed
        // TODO add your handling code here:
        try {
            if (this.tfUserID.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Please insert User ID", "Message", 2);
            } else if (this.tfUserID.getText().length() > 6) {
                JOptionPane.showMessageDialog(null, "Please insert 6 numbers", "Message", 2);
            } else {
                User user = new User(this.tfUserID.getText(), this.tfPass.getText(), this.tfName.getText(), this.tfBirthday.getText(),
                    this.tfIdentityNumber.getText(), this.tfPhoneNumber.getText(), this.tfAddress.getText());
                UserData.InsertUser(user);
                this.btSearchUser.doClick();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error!", "Message", 2);
        }
    }//GEN-LAST:event_btAddUserActionPerformed

    private void tbUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUserMouseClicked
        // TODO add your handling code here:
        ProcessCrt2(true);
        this.btAddUser.setEnabled(true);
        try {
            int row = this.tbUser.getSelectedRow();
            String IDrow = (this.tbUser.getModel().getValueAt(row, 0)).toString();
            String sql1 = "SELECT * FROM UserAccount where id='" + IDrow + "'";
            ResultSet rs = Update.ShowTextField(sql1);
            if (rs.next()) {
                this.tfUserID.setText(rs.getString("ID"));
                this.tfPass.setText(rs.getString("Password"));
                this.tfName.setText(rs.getString("Full Name"));
                this.tfBirthday.setText(rs.getString("Birthday"));
                this.tfIdentityNumber.setText(rs.getString("Identity Number"));
                this.tfPhoneNumber.setText(rs.getString("Phone Number"));
                this.tfAddress.setText(rs.getString("Address"));

            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_tbUserMouseClicked

    private void btReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReturnActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE BookList SET Quantity = ? where Code = ?";
        String sql1 = "SELECT Quantity from BookList where Code = '" + this.tfBookCode.getText() + "'";
        String sql2 = "UPDATE BorrowList SET ReturnDate = (select GETSSTRING()) where BorrowCode = ?";

        try {
            ps2 = JDBC_Connection.getConnect().prepareStatement(sql2);
            ps2.setString(1, this.tfBorrowCode.getText());
            ps2.executeQuery();
            this.btSearchBorrow.doClick();

            pst = JDBC_Connection.getConnect().prepareStatement(sql);
            ResultSet rs = Update.ShowTextField(sql1);
            pst.setString(2, this.tfBookCode.getText());
            int count = 0;
            if (rs.next()) {
                count = rs.getInt("Quantity");
            }

            pst.setInt(1, count + 1);
            pst.execute();
            this.btSearchBorrow.doClick();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btReturnActionPerformed

    private void btDeleteBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteBorrowActionPerformed
        // TODO add your handling code here:
        if (this.tfBorrowCode.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Please insert Borrow Code!", "Message", 2);
        } else {
            if (BorrowData.DeleteBorrow(this.tfBorrowCode.getText())) {
                JOptionPane.showMessageDialog(null, "Deleted!", "Message", 1);
            } else {
                JOptionPane.showMessageDialog(null, "Error. Please try again!", "Message", 2);
                this.btSearchBorrow.doClick();
            }
        }
    }//GEN-LAST:event_btDeleteBorrowActionPerformed

    private void btUpdateBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateBorrowActionPerformed
        // TODO add your handling code here:
        if (this.tfBorrowCode.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Please insert Borrow Code", "Message", 2);
        } else {
            Borrow borrow = new Borrow(this.tfBorrowCode.getText(), this.tfBorrowID.getText(),
                this.tfBookCode.getText(), this.tfBorrowDate.getText(), this.tfReturnDate.getText());
            if (BorrowData.UpdateBorrow(borrow)) {
                JOptionPane.showMessageDialog(null, "Updated!", "Message", 1);
            } else {
                JOptionPane.showMessageDialog(null, "Error!", "Message", 2);
            }
            this.btSearchBorrow.doClick();
        }
    }//GEN-LAST:event_btUpdateBorrowActionPerformed

    private void btAddBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddBorrowActionPerformed
        // TODO add your handling code here:
        try {
            if (this.tfBorrowCode.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Please insert Borrow Code", "Message", 2);
            } else {
                Borrow borrow = new Borrow(this.tfBorrowCode.getText(), this.tfBorrowID.getText(), this.tfBookCode.getText(),
                    this.tfBorrowDate.getText(), this.tfReturnDate.getText());
                BorrowData.InsertBorrow(borrow);
                this.btSearchBorrow.doClick();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error!", "Thông báo", 2);
        }

        String sql = "UPDATE BookList SET Quantity = ? where Code = ?";
        String sql1 = "SELECT Quantity from BookList where Code = '" + this.tfBookCode.getText() + "'";
        try {
            pst = JDBC_Connection.getConnect().prepareStatement(sql);
            ResultSet rs = Update.ShowTextField(sql1);
            pst.setString(2, this.tfBookCode.getText());
            int count = 0;
            if (rs.next()) {
                count = rs.getInt("Quantity");
            }
            pst.setInt(1, count - 1);
            pst.execute();
            this.btSearchBook.doClick();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btAddBorrowActionPerformed

    private void tfBorrowIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBorrowIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBorrowIDActionPerformed

    private void btSearchBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchBorrowActionPerformed
        // TODO add your handling code here:
        if (this.tfSearch.getText().length() == 0) {
            String sql1 = "SELECT * from BorrowList ";
            Update.LoadData(sql1, tbBorrow);
        } else {
            String sql1 = "SELECT * from BorrowList WHERE BorrowCode like N'%" + this.tfSearch.getText() + "%' "
            + "or ID like N'%" + this.tfSearch.getText() + "%'"
            + "or BookCode like N'%" + this.tfSearch.getText() + "%'";
            Update.LoadData(sql1, tbBorrow);
        }
    }//GEN-LAST:event_btSearchBorrowActionPerformed

    private void tbBorrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBorrowMouseClicked
        // TODO add your handling code here:
        ProcessCrt3(true);
        try {
            int row = this.tbBorrow.getSelectedRow();
            String IDrow = (this.tbBorrow.getModel().getValueAt(row, 0)).toString();
            String sql1 = "SELECT * FROM BorrowList where BorrowCode='" + IDrow + "'";
            ResultSet rs = Update.ShowTextField(sql1);
            if (rs.next()) {
                this.tfBorrowCode.setText(rs.getString("BorrowCode"));
                this.tfBorrowID.setText(rs.getString("ID"));
                this.tfBookCode.setText(rs.getString("BookCode"));
                this.tfBorrowDate.setText(rs.getString("BorrowDate"));
                this.tfReturnDate.setText(rs.getString("ReturnDate"));

            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_tbBorrowMouseClicked

    private void btDeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteBookActionPerformed
        // TODO add your handling code here:
        if (this.tfCode.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Please insert Book Code!", "Message", 2);
        } else {
            if (BookData.DeleteBook(this.tfCode.getText())) {
                JOptionPane.showMessageDialog(null, "Deleted", "Message", 1);
            } else {
                JOptionPane.showMessageDialog(null, "Error. Please try again!", "Message", 2);
                this.btSearchBook.doClick();
            }
        }
    }//GEN-LAST:event_btDeleteBookActionPerformed

    private void btUpdateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateBookActionPerformed
        // TODO add your handling code here:
        if (this.tfCode.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Please insert Book Code!", "Message", 2);
        } else {
            Book book = new Book(this.tfCode.getText(), this.tfBookName.getText(), this.tfAuthor.getText(), this.tfPublish.getText(),
                this.tfEdition.getText(), Float.parseFloat(this.tfCost.getText()), Integer.parseInt(this.tfQuantity.getText()));
            if (BookData.UpdateBook(book)) {
                JOptionPane.showMessageDialog(null, "Updated!", "Message", 1);
            } else {
                JOptionPane.showMessageDialog(null, "Fail.Please try again!", "Message", 2);
                this.btSearchBook.doClick();
            }
        }
    }//GEN-LAST:event_btUpdateBookActionPerformed

    private void btAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddBookActionPerformed
        // TODO add your handling code here:
        if (this.tfCode.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Please insert Book Code", "Message", 2);
        } else {
            Book book = new Book(this.tfCode.getText(), this.tfBookName.getText(), this.tfAuthor.getText(), this.tfPublish.getText(),
                this.tfEdition.getText(), Float.parseFloat(this.tfCost.getText()), Integer.parseInt(this.tfQuantity.getText()));
            BookData.InsertBook(book);
            this.btSearchBook.doClick();
        }
    }//GEN-LAST:event_btAddBookActionPerformed

    private void btSearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchBookActionPerformed
        // TODO add your handling code here:
        if (this.tfSearch.getText().length() == 0) {
            String sql1 = "SELECT * from BookList ";
            Update.LoadData(sql1, tbBook);
        } else {
            String sql1 = "SELECT * from BookList WHERE code like N'%" + this.tfSearch.getText() + "%' "
            + "or name like N'%" + this.tfSearch.getText() + "%'";
            Update.LoadData(sql1, tbBook);
        }
    }//GEN-LAST:event_btSearchBookActionPerformed

    private void tbBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBookMouseClicked
        // TODO add your handling code here:
        ProcessCrt(true);
        this.btAddBook.setEnabled(true);
        try {
            int row = this.tbBook.getSelectedRow();
            String IDrow = (this.tbBook.getModel().getValueAt(row, 0)).toString();
            String sql1 = "SELECT * FROM BookList where Code='" + IDrow + "'";
            ResultSet rs = Update.ShowTextField(sql1);
            if (rs.next()) {
                this.tfCode.setText(rs.getString("Code"));
                this.tfBookName.setText(rs.getString("Name"));
                this.tfAuthor.setText(rs.getString("Author"));
                this.tfPublish.setText(rs.getString("Publish"));
                this.tfEdition.setText((rs.getString("Edition")));
                this.tfCost.setText(rs.getString("Cost"));
                this.tfQuantity.setText(rs.getString("Quantity"));
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_tbBookMouseClicked

    public void GetUserList() {
        String sql1 = "SELECT * FROM UserAccount";
        Vector colss = new Vector();
        colss.addElement("ID");
        colss.addElement("Password");
        colss.addElement("Full Name");
        colss.addElement("Birhtday");
        colss.addElement("Identity Number");
        colss.addElement("Phone Number");
        colss.addElement("Address");
        tbUser.setModel(new DefaultTableModel(null, colss));
        Vector userData = new Vector();
        try {
            pst = JDBC_Connection.getConnect().prepareStatement(sql1);
            rs = pst.executeQuery();
            while (rs.next()) {
                Vector user = new Vector();
                user.addElement((rs.getString("ID")));
                user.addElement((rs.getString("Password")));
                user.addElement((rs.getString("Full Name")));
                user.addElement((rs.getString("Birhtday")));
                user.addElement((rs.getString("Identity Number")));
                user.addElement((rs.getFloat("Phone Number")));
                user.addElement((rs.getInt("Address")));
            }
            Update.LoadData(sqlUser, tbUser);
        } catch (Exception e) {

        }
    }

    public void GetBorrowList() {
        String sql1 = "SELECT * FROM BorrowList";
        Vector col = new Vector();
        col.addElement("BorrowCode");
        col.addElement("ID");
        col.addElement("BookCode");
        col.addElement("BorrowDate");
        col.addElement("ReturnDate");

        tbBorrow.setModel(new DefaultTableModel(null, col));
        Vector borrowData = new Vector();
        try {
            pst = JDBC_Connection.getConnect().prepareStatement(sql1);
            rs = pst.executeQuery();
            while (rs.next()) {
                Vector borrow = new Vector();
                borrow.addElement((rs.getString("BorrowCode")));
                borrow.addElement((rs.getString("ID")));
                borrow.addElement((rs.getString("BookCode")));
                borrow.addElement((rs.getString("BorrowDate")));
                borrow.addElement((rs.getString("ReturnDate")));
            }
            Update.LoadData(sqlBorrow, tbBorrow);
        } catch (Exception e) {

        }
    }

    public void GetBooklist() {

        String sql1 = "SELECT * FROM BookList";
        Vector cols = new Vector();
        cols.addElement("Code");
        cols.addElement("Name");
        cols.addElement("Author");
        cols.addElement("Publish");
        cols.addElement("Edition");
        cols.addElement("Cost");
        cols.addElement("Quantity");
        tbBook.setModel(new DefaultTableModel(null, cols));
        Vector bookData = new Vector();
        try {
            pst = JDBC_Connection.getConnect().prepareStatement(sql1);
            rs = pst.executeQuery();
            while (rs.next()) {
                Vector book = new Vector();
                book.addElement((rs.getString("Code")));
                book.addElement((rs.getString("Name")));
                book.addElement((rs.getString("Author")));
                book.addElement((rs.getString("Publish")));
                book.addElement((rs.getString("Edition")));
                book.addElement((rs.getFloat("Cost")));
                book.addElement((rs.getInt("Quantity")));
            }
            Update.LoadData(sqlBook, tbBook);
        } catch (Exception e) {

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddBook;
    private javax.swing.JButton btAddBorrow;
    private javax.swing.JButton btAddUser;
    private javax.swing.JButton btDeleteBook;
    private javax.swing.JButton btDeleteBorrow;
    private javax.swing.JButton btDeleteUser;
    private javax.swing.JButton btReturn;
    private javax.swing.JButton btSearchBook;
    private javax.swing.JButton btSearchBorrow;
    private javax.swing.JButton btSearchUser;
    private javax.swing.JButton btUpdateBook;
    private javax.swing.JButton btUpdateBorrow;
    private javax.swing.JButton btUpdateUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbBook;
    private javax.swing.JTable tbBorrow;
    private javax.swing.JTable tbUser;
    private javax.swing.JTextArea tfAddress;
    private javax.swing.JTextField tfAuthor;
    private javax.swing.JTextField tfBirthday;
    private javax.swing.JTextField tfBookCode;
    private javax.swing.JTextField tfBookName;
    private javax.swing.JTextField tfBorrowCode;
    private javax.swing.JTextField tfBorrowDate;
    private javax.swing.JTextField tfBorrowID;
    private javax.swing.JTextField tfCode;
    private javax.swing.JTextField tfCost;
    private javax.swing.JTextField tfEdition;
    private javax.swing.JTextField tfIdentityNumber;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPass;
    private javax.swing.JTextField tfPhoneNumber;
    private javax.swing.JTextField tfPublish;
    private javax.swing.JTextField tfQuantity;
    private javax.swing.JTextField tfReturnDate;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfSearchBorrow;
    private javax.swing.JTextField tfSearchUser;
    private javax.swing.JTextField tfUserID;
    // End of variables declaration//GEN-END:variables

}
