/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagement;

import java.sql.*;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import librarymanagement.LibraryManagementProgramme;
import librarymanagement.LogIn;
import data.JDBC_Connection;
import data.User;
import data.UserData;

/**
 *
 * @author qinee
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfPass = new javax.swing.JPasswordField();
        tfRePass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbMessageID = new javax.swing.JLabel();
        btCancel = new javax.swing.JButton();
        btRegister = new javax.swing.JButton();
        lbMessagePass = new javax.swing.JLabel();
        btLogIn = new javax.swing.JButton();
        lbMessageRePass1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfID = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfAddress = new javax.swing.JTextArea();
        lbMessageIdentityNum = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbBirthday1 = new javax.swing.JLabel();
        tfBirthday = new javax.swing.JTextField();
        tfPhone = new javax.swing.JFormattedTextField();
        tfIdentityNum = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Register");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btID.setText("ID");

        jLabel2.setText("Password");

        jLabel3.setText("Re-enter password");

        tfPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfPassMousePressed(evt);
            }
        });
        tfPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPassActionPerformed(evt);
            }
        });
        tfPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPassKeyPressed(evt);
            }
        });

        tfRePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfRePassMousePressed(evt);
            }
        });
        tfRePass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfRePassKeyPressed(evt);
            }
        });

        jLabel4.setText("Full Name");

        tfName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfNameMousePressed(evt);
            }
        });
        tfName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNameKeyPressed(evt);
            }
        });

        jLabel5.setText("Address");

        jLabel6.setText("Birthday");

        jLabel7.setText("Identity Number");

        lbMessageID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbMessageID.setForeground(new java.awt.Color(255, 0, 0));
        lbMessageID.setText("*");
        lbMessageID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMessageIDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMessageIDMouseEntered(evt);
            }
        });

        btCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btCancel.setForeground(new java.awt.Color(0, 0, 255));
        btCancel.setText("Cancel");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        btRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btRegister.setForeground(new java.awt.Color(0, 0, 255));
        btRegister.setText("Register");
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterActionPerformed(evt);
            }
        });

        lbMessagePass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbMessagePass.setForeground(new java.awt.Color(255, 0, 0));
        lbMessagePass.setText("*");
        lbMessagePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMessagePassMouseClicked(evt);
            }
        });

        btLogIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btLogIn.setForeground(new java.awt.Color(0, 0, 255));
        btLogIn.setText("Log In");
        btLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogInActionPerformed(evt);
            }
        });

        lbMessageRePass1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbMessageRePass1.setForeground(new java.awt.Color(255, 0, 0));
        lbMessageRePass1.setText("*");
        lbMessageRePass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMessageRePass1MouseClicked(evt);
            }
        });

        jLabel8.setText("Phone Number");

        tfID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDActionPerformed(evt);
            }
        });
        tfID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfIDKeyPressed(evt);
            }
        });

        tfAddress.setColumns(20);
        tfAddress.setRows(5);
        jScrollPane1.setViewportView(tfAddress);

        lbMessageIdentityNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbMessageIdentityNum.setForeground(new java.awt.Color(255, 0, 0));
        lbMessageIdentityNum.setText("*");
        lbMessageIdentityNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMessageIdentityNumMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMessageIdentityNumMouseEntered(evt);
            }
        });

        jLabel1.setText("* is compulsory. Click on each * for more information.");

        lbName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbName.setForeground(new java.awt.Color(255, 0, 0));
        lbName.setText("*");
        lbName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbNameMouseEntered(evt);
            }
        });

        lbBirthday1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbBirthday1.setForeground(new java.awt.Color(255, 0, 0));
        lbBirthday1.setText("*");
        lbBirthday1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBirthday1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbBirthday1MouseEntered(evt);
            }
        });

        tfPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPhoneActionPerformed(evt);
            }
        });
        tfPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPhoneKeyPressed(evt);
            }
        });

        tfIdentityNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdentityNumActionPerformed(evt);
            }
        });
        tfIdentityNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfIdentityNumKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(btID)
                            .addComponent(jLabel6))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfID)
                                .addGap(18, 18, 18)
                                .addComponent(lbMessageID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfPass, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfRePass, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfName, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(tfBirthday)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(tfIdentityNum)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbMessageIdentityNum, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lbMessagePass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbMessageRePass1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbBirthday1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                    .addComponent(tfPhone)))
                            .addComponent(jLabel1))
                        .addGap(0, 56, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbMessageID)
                        .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMessagePass))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfRePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMessageRePass1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(lbName)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lbBirthday1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tfBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMessageIdentityNum)
                    .addComponent(jLabel7)
                    .addComponent(tfIdentityNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(tfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRegister)
                    .addComponent(btCancel)
                    .addComponent(btLogIn))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")


    private void btRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterActionPerformed

        // TODO add your handling code here:
        try {

            User user = new User(this.tfID.getText(), this.tfPass.getText(), this.tfName.getText(), this.tfBirthday.getText(),
                    this.tfIdentityNum.getText(), this.tfPhone.getText(), this.tfAddress.getText());
            UserData.InsertUser(user);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error!", "Message", 2);
        }
    }//GEN-LAST:event_btRegisterActionPerformed


    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        LibraryManagementProgramme frmLibraryManagementProgramme = new LibraryManagementProgramme();
        frmLibraryManagementProgramme.setVisible(true);
    }//GEN-LAST:event_btCancelActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Do you want to exit?", "Message", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void lbMessageIDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMessageIDMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_lbMessageIDMouseEntered

    private void lbMessageIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMessageIDMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Please enter 6 numbers!", "Message", JOptionPane.OK_OPTION);
    }//GEN-LAST:event_lbMessageIDMouseClicked

    private void lbMessagePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMessagePassMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Please enter at least 8 characters!", "Message", JOptionPane.OK_OPTION);
    }//GEN-LAST:event_lbMessagePassMouseClicked

    private void btLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogInActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        LogIn frmLogIn = new LogIn();
        frmLogIn.setVisible(true);
    }//GEN-LAST:event_btLogInActionPerformed

    private void tfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPassActionPerformed

    private void lbMessageRePass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMessageRePass1MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Please input password again!", "Message", JOptionPane.OK_OPTION);
    }//GEN-LAST:event_lbMessageRePass1MouseClicked

    private void lbMessageIdentityNumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMessageIdentityNumMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Please enter 11 numbers!", "Message", JOptionPane.OK_OPTION);

    }//GEN-LAST:event_lbMessageIdentityNumMouseClicked

    private void lbMessageIdentityNumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMessageIdentityNumMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbMessageIdentityNumMouseEntered

    private void tfPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPassKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            if ((tfPass.getText().length() <= 7)) {
                JOptionPane.showMessageDialog(this, "Please enter at least 8 characters.\n", "Message", JOptionPane.ERROR_MESSAGE);
                tfPass.requestFocus();
            } else {
                tfRePass.requestFocus();
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if ((tfPass.getText().length() <= 7)) {
                JOptionPane.showMessageDialog(this, "Please enter at least 8 characters.\n", "Message", JOptionPane.ERROR_MESSAGE);
                tfPass.requestFocus();
            } else {
                tfRePass.requestFocus();
            }
        } else {
            tfPass.requestFocus();
        }
    }//GEN-LAST:event_tfPassKeyPressed

    private void tfRePassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRePassKeyPressed
        // TODO add your handling code here:
        String pass = tfPass.getText();
        String repass = tfRePass.getText();

        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            if (!pass.equals(repass)) {
                JOptionPane.showMessageDialog(this, "Password do not match. Please try again.\n", "Message", JOptionPane.ERROR_MESSAGE);
                tfRePass.requestFocus();
            } else {
                tfName.requestFocus();
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!pass.equals(repass)) {
                JOptionPane.showMessageDialog(this, "Password do not match. Please try again.\n", "Message", JOptionPane.ERROR_MESSAGE);
                tfRePass.requestFocus();
            } else {
                tfName.requestFocus();
            }
        } else {
            tfRePass.requestFocus();
        }
    }//GEN-LAST:event_tfRePassKeyPressed

    private void tfNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            if (tfName.getText() == null) {
                tfName.requestFocus();
            } else {
                tfBirthday.requestFocus();
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (tfName.getText() == null) {
                tfName.requestFocus();
            } else {
                tfBirthday.requestFocus();
            }
        }
    }//GEN-LAST:event_tfNameKeyPressed

    private void tfIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIDKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            if (this.tfID.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Please insert User ID", "Message", 2);
                tfID.requestFocus();
            } else if (this.tfID.getText().length() != 6) {
                JOptionPane.showMessageDialog(null, "Please insert 6 characters!", "Message", 2);
                tfID.requestFocus();
            } else {
                tfPass.requestFocus();
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (this.tfID.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Please insert User ID", "Message", 2);
                tfID.requestFocus();
            } else if (this.tfID.getText().length() != 6) {
                JOptionPane.showMessageDialog(null, "Please insert 6 characters!", "Message", 2);
                tfID.requestFocus();
            } else {
                tfPass.requestFocus();
            }
        }
    }//GEN-LAST:event_tfIDKeyPressed

    private void tfPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPassMousePressed
        // TODO add your handling code here:
        if (this.tfID.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Please insert User ID", "Message", 2);
            tfID.requestFocus();
        } else if (this.tfID.getText().length() != 6) {
            JOptionPane.showMessageDialog(null, "Please insert 6 characters!", "Message", 2);
            tfID.requestFocus();
        } else {
            tfPass.requestFocus();
        }
    }//GEN-LAST:event_tfPassMousePressed

    private void tfRePassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfRePassMousePressed
        // TODO add your handling code here:
        if ((tfPass.getText().length() <= 7)) {
            JOptionPane.showMessageDialog(this, "Please enter at least 8 characters.\n", "Message", JOptionPane.ERROR_MESSAGE);
            tfPass.requestFocus();
        } else {
            tfRePass.requestFocus();
        }
    }//GEN-LAST:event_tfRePassMousePressed

    private void tfNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNameMousePressed
        // TODO add your handling code here:
        String pass = tfPass.getText();
        String repass = tfRePass.getText();

        if (!pass.equals(repass)) {
            JOptionPane.showMessageDialog(this, "Password do not match. Please try again.\n", "Message", JOptionPane.ERROR_MESSAGE);
            tfRePass.requestFocus();
        } else {
            tfName.requestFocus();
        }
    }//GEN-LAST:event_tfNameMousePressed

    private void tfIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDActionPerformed

    private void lbNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbNameMouseClicked

    private void lbNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNameMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbNameMouseEntered

    private void lbBirthday1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBirthday1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbBirthday1MouseClicked

    private void lbBirthday1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBirthday1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbBirthday1MouseEntered

    private void tfPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPhoneActionPerformed

    private void tfPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPhoneKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tfPhoneKeyPressed

    private void tfIdentityNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdentityNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdentityNumActionPerformed

    private void tfIdentityNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIdentityNumKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            if (this.tfIdentityNum.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Please insert Identity Number!", "Message", 2);
                tfIdentityNum.requestFocus();
            } else if (this.tfIdentityNum.getText().length() != 11) {
                JOptionPane.showMessageDialog(null, "Please insert 11 numbers!", "Message", 2);
                tfIdentityNum.requestFocus();
            } else {
                tfPhone.requestFocus();
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (this.tfIdentityNum.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Please insert Identity Number!", "Message", 2);
                tfIdentityNum.requestFocus();
            } else if (this.tfIdentityNum.getText().length() != 11) {
                JOptionPane.showMessageDialog(null, "Please insert 11 numbers!", "Message", 2);
                tfIdentityNum.requestFocus();
            } else {
                tfPhone.requestFocus();
            }
        }
    }//GEN-LAST:event_tfIdentityNumKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
                JDBC_Connection.getConnect();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JLabel btID;
    private javax.swing.JButton btLogIn;
    private javax.swing.JButton btRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBirthday1;
    private javax.swing.JLabel lbMessageID;
    private javax.swing.JLabel lbMessageIdentityNum;
    private javax.swing.JLabel lbMessagePass;
    private javax.swing.JLabel lbMessageRePass1;
    private javax.swing.JLabel lbName;
    private javax.swing.JTextArea tfAddress;
    private javax.swing.JTextField tfBirthday;
    private javax.swing.JFormattedTextField tfID;
    private javax.swing.JFormattedTextField tfIdentityNum;
    private javax.swing.JTextField tfName;
    private javax.swing.JPasswordField tfPass;
    private javax.swing.JFormattedTextField tfPhone;
    private javax.swing.JPasswordField tfRePass;
    // End of variables declaration//GEN-END:variables
}
